### PR TITLE
Allow several twittos conversation.

### PR DESCRIPTION
**Pull request by Ezibenroc**
With this fix, if `@bla` twitts `@askplatypus @foo @bar What is the capital of France?`, the bot will answer `@bla @foo @bar Paris`.

This allows to query the bot within a conversation on twitter.

This also allows to have the names of the twittos wherever you want in the sentence (e.g. `What is the receipe of falafels? @askplatypus`).

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Please note that this code was not tested.

**Comment by Ezibenroc** [comment]
@ProgVal Merge?

**Comment by progval** [comment]
you forgot underscores in the regexp

**Comment by Ezibenroc** [comment]
Fixed (I also forgot digits).

**Pull request merged**
